# Generated by Django 4.2.2 on 2023-08-23 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abn', models.CharField(blank=True, max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tokens_used', models.BigIntegerField(blank=True, default=0)),
                ('monthly_tokens_used', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('system_context', models.TextField(blank=True, default='')),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gptform.company')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('absolute_max_tokens', models.PositiveIntegerField(blank=True, default=0)),
                ('warning_max_tokens', models.PositiveIntegerField(blank=True, default=0)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('allowed_models', models.TextField(blank=True, default='')),
                ('duration_days', models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the licence in days.')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('field_type', models.PositiveSmallIntegerField(choices=[(0, 'SINGLE_TEXT'), (1, 'MULTI_TEXT'), (2, 'DATE'), (3, 'CHECKBOX')])),
                ('prefill', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('parent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gptform.form')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='licence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gptform.licence'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
